#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := radiolog_app

EXTRA_COMPONENT_DIRS := /Users/asterix/src/esp/esp-idf-lib/components
EXCLUDE_COMPONENTS := max7219 mcp23x17 led_strip max31865

include $(IDF_PATH)/make/project.mk
